# Generated by Django 4.0.6 on 2022-07-16 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=20)),
                ('Category', models.CharField(max_length=20)),
                ('FeaturedImage', models.CharField(max_length=100)),
                ('Price', models.CharField(max_length=20)),
                ('StockCount', models.IntegerField()),
            ],
        ),
    ]
