# Generated by Django 4.0.6 on 2022-07-20 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Quantity', models.IntegerField()),
                ('Price', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=20)),
                ('Category', models.CharField(max_length=20)),
                ('FeaturedImage', models.TextField()),
                ('Price', models.CharField(max_length=10)),
                ('StockCount', models.IntegerField()),
                ('Description', models.TextField()),
                ('Features', models.JSONField()),
                ('AdditionalImages', models.JSONField()),
                ('Reviews', models.JSONField()),
            ],
        ),
    ]
